name: Auto PR from Test to Main

on:
  workflow_run:
    workflows: ["Test CI"]
    types: [completed]
    branches: [test]  

jobs:
  create-pull-request:
    if: >-
      ${{ 
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'workflow_run'
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Test Branch
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          base: main  
          head: test  
          title: "Auto PR: Merge Test into Main"
          body: |
            **Automated PR - Test Results**  
            All tests passed in [Test CI](${{ github.event.workflow_run.html_url }})  
            Generated at: ${{ github.event.workflow_run.updated_at }}  
          labels: automated, test-passed
          reviewers: Faziee,Jordana-GC
          assignees: Faziee,Jordana-GC
          draft: false
