name: Main CI and Deployment

on:
  push:
    branches:
      - main 

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github 
          settings-path: ${{ github.workspace }}/.github/maven 

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Full Tests
        run: mvn test

      - name: Deploy to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/maven/settings.xml -Denv=production -X
        env:
          GITHUB_TOKEN: ${{ github.token }}
