name: Auto-Merge Dev to Test

on:
  push:
    branches: [dev]
  workflow_dispatch: 

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    outputs:
      was_merged: ${{ steps.merge.outputs.was_merged }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge dev into test
        id: merge
        run: |
          git checkout test
          if git merge --no-ff dev -m "Auto-merged dev into test"; then
            git push
            echo "was_merged=true" >> $GITHUB_OUTPUT
            echo "MERGE_SUCCESS=true" >> $GITHUB_ENV 
          else
            echo "was_merged=false" >> $GITHUB_OUTPUT
            exit 1
          fi
