name: Test CI

on:
  workflow_run:
    workflows: ["Auto-Merge Dev to Test"]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Branch
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0
          clean: true

      - name: Verify POM
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "::error::pom.xml missing!"
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests -B

      - name: Run Tests
        run: mvn test -B
