name: Test CI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto-Merge Dev to Test"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (Forced)
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0
          clean: false  

      - name: Find POM File (Nuclear Verification)
        run: |
          echo "=== FULL REPO STRUCTURE ==="
          find . -type f | sort
          echo "=== POM FILE CHECK ==="
          if [ ! -f "pom.xml" ]; then
            echo "::error::CRITICAL: pom.xml is MISSING from root directory!"
            echo "Current files in root:"
            ls -la
            exit 1
          else
            echo "POM FOUND - Contents:"
            head -n 10 pom.xml
          fi