name: Test CI

on:
  workflow_run:
    workflows: ["Auto-Merge Dev to Test"]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./project-root 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0
          path: project-root 

      - name: Verify Files
        run: |
          echo "=== WORKING DIRECTORY ==="
          pwd
          echo "=== FULL FILE STRUCTURE ==="
          find . -type f | sort
          echo "=== POM VERIFICATION ==="
          if [ -f "project-root/pom.xml" ]; then
            echo "POM EXISTS at project-root/pom.xml"
            ls -la project-root/
          else
            echo "::error::POM NOT FOUND!"
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: project-root  
        run: mvn clean install -DskipTests -B -e

      - name: Run Tests
        working-directory: project-root  
        run: mvn test -B
