name: Test CI

on:
  workflow_run:
    workflows: ["Auto-Merge Dev to Test"]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./project-root
    steps:
      - name: Checkout with Debug
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0
          path: ${{ env.WORKING_DIR }}
        
      - name: Nuclear File Verification
        run: |
          echo "=== FULL DIRECTORY TREE ==="
          find ${{ env.WORKING_DIR }} -type d | sort
          echo "=== POM VERIFICATION ==="
          if [ -f "${{ env.WORKING_DIR }}/pom.xml" ]; then
            echo "POM FOUND at ${{ env.WORKING_DIR }}/pom.xml"
            echo "POM CONTENTS:"
            head -n 20 "${{ env.WORKING_DIR }}/pom.xml"
          else
            echo "::error::POM NOT FOUND IN ${{ env.WORKING_DIR }}!"
            echo "Current files:"
            ls -la ${{ env.WORKING_DIR }}
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (Debug Mode)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "=== MAVEN DEBUG ==="
          mvn help:effective-pom -Doutput=effective-pom.xml
          head -n 20 effective-pom.xml
          mvn clean install -DskipTests -X

      - name: Run Tests
        working-directory: ${{ env.WORKING_DIR }}
        run: mvn test
