name: Test CI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto-Merge Dev to Test"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hard Reset Checkout
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0
          clean: true  

      - name: Nuclear File Verification
        run: |
          echo "=== FULL REPO DUMP ==="
          find . -type f
          echo "=== POM VALIDATION ==="
          if [ -f "pom.xml" ]; then
            echo "POM EXISTS at $(pwd)/pom.xml"
            echo "First 10 lines:"
            head -n 10 pom.xml
          else
            echo "::error::POM NOT FOUND IN ROOT DIRECTORY!"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Force Maven Build
        run: |
          echo "=== MAVEN NUCLEAR DEBUG ==="
          mvn -X -e clean install -DskipTests
