name: Test CI

on:
  workflow_run:
    workflows: ["Auto-Merge Dev to Test"]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (Forced)
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0
          clean: false  

      - name: Find POM File (Nuclear Verification)
        run: |
          echo "=== FULL REPO STRUCTURE ==="
          find . -type f | sort
          echo "=== POM FILE CHECK ==="
          if [ ! -f "pom.xml" ]; then
            echo "::error::CRITICAL: pom.xml is MISSING from root directory!"
            echo "Current files in root:"
            ls -la
            exit 1
          else
            echo "POM FOUND - Contents:"
            head -n 10 pom.xml
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (Absolute Path)
        run: |
          echo "Current directory: $(pwd)"
          mvn -f pom.xml clean install -DskipTests -B -e -X

      - name: Run Tests
        run: mvn test -B
